### ISSUE TITLE
Support xz method.

### ISSUE THREAD

**Issue by Yukari0201** [MMRLApp/MMRL-Util#15]
`modules/zygisk_shamiko/track.yaml`
```yaml
id: zygisk_shamiko
enable: true
verified: true
update_to: https://lsposed.github.io/releases/shamiko.json
source: https://github.com/LSPosed/LSPosed.github.io
versions: 1
```

When running `mmrl-util sync`, you will get the following ERROR message.
```
[2025/06/27 15:44:15] Pull ERROR: _from_zip_common: [zygisk_shamiko] -> MagiskModuleError(Error reading 'module.prop' from '/home/***/***/mmrl-repo/modules/zygisk_shamiko/zygisk_shamiko.zip': That compression method is not supported).
```

I then manually downloaded the file `Shamiko-v1.2.5-414-release.zip` mentioned by `“zipUrl”` in https://lsposed.github.io/releases/shamiko.json and used the 7-zip command line tool to view the information of `module.prop`.
`$ 7z l -slt -ba Shamiko-v1.2.5-414-release.zip`
```
...

Path = module.prop
Folder = -
Size = 210
Packed Size = 232
Modified = 2025-06-16 06:07:46
Created = 
Accessed = 
Attributes =  -rw-r--r--
Encrypted = -
Comment = 
CRC = 7243198C
Method = xz
Characteristics = UTF8
Host OS = Unix
Version = 10
Volume Index = 0
Offset = 6520701

...
```

Now we can be sure that the ERROR is caused by the fact that MMRL-Util does not support xz compression.

Remind me if you need more information.

Also, I'm not good at using English, so I used machine translation. Please feel free to alert me if there is something you can't understand.
